m: 114.1 # kg
I_z: 19.41 # kg/m2
x_g: -0.1 
y_g: 0.0


# Added mass terms
X_u_dot: -9.59
Y_v_dot: -5.73
Y_r_dot: 0.0
N_v_dot: 0.0
N_r_dot: -30.21

# Linear damping terms [X_u, Y_v, Y_r, N_v, N_r]
X_u: -3.02
X_v: 0.0
Y_v: -3.72
Y_r: -39.85
N_v: 1.72
N_r: -13.73

# Nonlinear damping terms [X_|u|u, Y_|v|v, N_|r|r, X_uuu, Y_vvv, N_rrr]
X_uu:  -4.84
X_uuu:  -18.66
X_vv: 0
X_vvv: 0
Y_vv: -133
Y_vvv:  -206.42
Y_rr: -21.75
Y_rrr: 0.0
Y_rv: -3.85
Y_vr: -4.05
N_rr:   -6.22
N_rrr:  0.0
N_vv: 3.96
N_vvv: 0.0
N_rv: 0.82
N_vr: 0.5

K_thruster: 0.000013888889

dt: 0.05